######################################################
### Fit the classification model with testing data ###
######################################################

### Author: Yuting Ma(The first "test" function)
###         Boxuan Zhao(Test.SVM)
### Project 3
### ADS Spring 2016

test <- function(fit_train, dat_test){
  
  ### Fit the classfication model with testing data
  
  ### Input: 
  ###  - the fitted classification model using training data
  ###  -  processed features from testing images 
  ### Output: training model specification
  
  ### load libraries
  library("gbm")
  
  pred <- predict(fit_train$fit, newdata=dat_test, 
                  n.trees=fit_train$iter, type="response")
  
  return(as.numeric(pred> 0.5))
}

Test.SVM = function(model,val,class)
{
  ### Fit the classfication model(SVM) with testing data
  
  ### Input: 
  ###  -  model : the model
  ###  -  val : validation data set, with each row as an observation
  ###  -  class : a vector of classes for each observation of val
  ### Output: the predicted classes generated by model on validation data set
  pred <- predict(model,val)
  
  return(mean(pred != class))
}
